### ISSUE TITLE
Undefined var in OBJ_mysql.php (line 447)

### ISSUE THREAD

**Issue by liquorandbeer** [entomb/OBJ-MySQL#10]
Hello,

line 447 of OBJ_mysql.php contains an undefined variable.
$item has to be replace with $var to work properly.

Current line 447:
$var = "'".round(floatval(str_replace(",",".",$item)),6)."'";

But besides that you wrote a nice class!
Best regards.

**Comment by entomb** [comment]
thanks a lot!
