### ISSUE TITLE
Could you change UTF-8 to utf8 as default value for charset

### ISSUE THREAD

**Issue by UnsupportedCallbackException** [entomb/OBJ-MySQL#11]
I think "UTF-8" incorrect because I have "???? ??" in non-english string values. And seems  "utf8" work better to me.

All examples that I find used "utf8"
http://stackoverflow.com/questions/10829816/php-set-character-names-using-mysqli 
http://www.php.net/manual/en/mysqli.set-charset.php

Thanks

**Comment by entomb** [comment]
Done! thanks for the bug report!
