### ISSUE TITLE
Logs might cause memory leak

### ISSUE THREAD

**Issue by UnsupportedCallbackException** [entomb/OBJ-MySQL#12]
I have loop with >50k iterations. (Social network API calls). Each call I save some data and my SQL request pushed ups to logs array. 

Maybe it's better to add some logSize and/or enableLogs props to class config? Or at least clearLogs() method.

After all I really like your lib.

**Comment by entomb** [comment]
Done, 
you now have a new config `$config["allow_logging"] = "TRUE|FALSE";` that you can set when you instance the class. can you give it a go, tell me if it suits your need?

thanks for using it, btw, its more of a personal lib but its nice too see it useful to somebody else
