### ISSUE TITLE
Add num rows functions

### ISSUE THREAD

**Issue by Codez1337** [entomb/OBJ-MySQL#5]
We need a num rows function added.

**Comment by entomb** [comment]
Hello @Codez1337 ,

You can use `$result->num_rows`, it's a property rather than a method but it will hold how many rows the resultset has.

for `affected_rows` you have the `$db->affected_rows()` method and you should call right after your query.

example:

``` php

$result = $db->query("SELECT * FROM users");
echo $result->num_rows; //how many users


$db->query("DELETE from users WHERE active = 0");
echo $db->affected_rows() //how many rows were deleted;

```

**Comment by Codez1337** [comment]
a question which i must ask and may look stupid, but how do you use that in an if statement? 

i want to count the rtows and if there are not enough then exit that part of the script. now i know that the old mysql way works but i am trying to get into using classes and oop so how would i do it with this? 

I ask because i am getting errors trying to do it the old way.

**Comment by entomb** [comment]
well its quite simple, properties work like variables, actually this `num_rows` is a direct property from the native php `mysqli` object.

so you can use it like this

``` php
if($result->num_rows==0){
//empty
}

if(!$result->num_rows){
//empty
}
```

or like this:

``` php
if($result->num_rows){
//not empty!
}
```

**Comment by Codez1337** [comment]
so the var i name the query becomes an object?

**Comment by entomb** [comment]
@Codez1337 , well, yes, it returns a resultset object that helps you access your data
