### ISSUE TITLE
warning in mysqli_connect

### ISSUE THREAD

**Issue by mdomba** [entomb/OBJ-MySQL#8]
when there is an error in the config... like a wrong database name... mysqli_connect issues a warning like

```
Warning: mysqli_connect(): (HY000/1049): Unknown database 'x' in OBJ_mysql.php on line 104
```

a solution would be to use `@mysqli_connect()`

**Comment by entomb** [comment]
I'm going to let this fly, if you are using a wrong database name you WANT that warning, and silencing the `@mysqli_connect()` would make it harder for you to figure it out. 

Am I missing anything before I close? would love to hear your opinion on this

**Comment by mdomba** [comment]
My idea was to silence the "ugly" default message.

If you enter a wrong database name or any similar error and silence the connect the code just after the connect will display a user friendly error message so nothing is lost.

Thats why on #9 I suggested to add the database and hostname information, too.

**Comment by entomb** [comment]
Done!, don't be afraid to pull request next time, I love merging code ;)

**Comment by mdomba** [comment]
To tell the truth I was not sure you are still active on this project, so I just commented to see how it will go :)

Btw, now on #9 the hostname/database name are missing.
