### ISSUE TITLE
Better error message in case of failed database connection

### ISSUE THREAD

**Issue by mdomba** [entomb/OBJ-MySQL#9]
If mysqli_connect fails the current error message is
`"Error connecting to mysql server"`

How about giving more info like the database and hostname like

`"Error connecting to mysql database '$this->database' on server '$this->hostname'"`

**Comment by mdomba** [comment]
In fact, it would make sense to add the message from `mysql_connect_error()` so OBJ_mysql.php line 108 would become like

```
$this->_displayError("Error connecting to mysql database '$this->database' on server '$this->hostname'");
$this->_displayError(mysqli_connect_error());
```

**Comment by entomb** [comment]
Fixed as suggested! thanks for the input
